package ru.nsu.titov.model.playfield;

public enum WallType {
    SINGLE, HORIZONTAL, VERTICAL, CORNER_UP_RIGHT, CORNER_RIGHT_DOWN, CORNER_DOWN_LEFT, CORNER_LEFT_UP,
    X_SHAPED, T_LEFT, T_RIGHT, T_UP, T_DOWN, LEFT, UP, DOWN, RIGHT
}
